DIR_LAB               = lab
NAME                  = spring-io-guides
IMAGE_SOURCE          = https://github.com/spring-academy/spring-io-guides
CONTAINER_REGISTRY    = 
CONTAINER_REPOSITORY  = spring-io-guides
version               = latest

env                   = local