apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-io-rest-service
spec:
  title: Building a RESTful Web Service
  description: "Building a RESTful Web Service"
  workshop:
    image: jdk17-environment:*
    files:
      - http:
          url: "$(ingress_protocol)://$(assets_repository)/$(workshop_name).tar.gz"
        includePaths:
          - /workshop/**
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/gs-rest-service.git
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LAB_VERSION
        value: "${VERSION}"
      - name: WEBSERVER
        value: "$(ingress_protocol)://$(assets_repository)"
    namespaces:
      budget: medium
    resources:
      memory: 3Gi
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: true
    dashboards:
      - name: Editor
      - name: Terminal
  environment:
    assets:
      memory: 0Mi
      ingress:
        enabled: true
      files:
        - image:
            url: ${CONTAINER_REGISTRY}${CONTAINER_REPOSITORY}:${VERSION}
          newRootPath: usr/share/nginx/html
