apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: spring-io-guides
spec:
  portal:
    title: Spring Academy / Spring IO Guides
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 180
    theme:
      frame:
        ancestors:
        - https://spring.academy
        - https://*.spring.academy
        - https://*.vmware.com
        - https://*.broadcom.com
        - https://spring-staging.academy
        - https://spring-academy.broadcom.com
        - https://spring-academy-verify.broadcom.com
        - https://spring-academy-qa.broadcom.net
        - https://spring-academy-dev.broadcom.net
        - http://localhost:8080
  analytics:
    google:
      trackingId: "${ANALYTICS_GOOGLE_ID}"
    clarity:
      trackingId: "${ANALYTICS_CLARITY_ID}"
  workshops:
    - name: spr-io-messaging-with-rabbitmq
      capacity: 1
      expires: 60m
      orphaned: 5m
      reserved: ${TRAINING_PORTAL_RESERVED}
    - name: spr-io-building-an-application-with-spring-boot
      capacity: 1
      expires: 60m
      orphaned: 5m
      reserved: ${TRAINING_PORTAL_RESERVED}
    - name: spr-io-accessing-data-jpa
      capacity: 1
      expires: 60m
      orphaned: 5m
      reserved: ${TRAINING_PORTAL_RESERVED}
    - name: spr-io-rest-service
      capacity: 1
      expires: 60m
      orphaned: 5m
      reserved: ${TRAINING_PORTAL_RESERVED}
