apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-io-messaging-with-rabbitmq
spec:
  title: Messaging with RabbitMQ
  description: "Messaging with RabbitMQ"
  workshop:
    image: jdk17-environment:*
    files:
      - image: # Note: format is {repository-name}-files
          url: $(image_repository)/spring-io-guides-files:$(workshop_version)
        includePaths:
          - /workshops/messaging-with-rabbitmq/workshop/**
        newRootPath: workshops/messaging-with-rabbitmq
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/gs-messaging-rabbitmq.git
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: true
      docker:
        enabled: true
        storage: 500Mi
        socket:
          # you must have this to enable docker ps, etc.
          enabled: true
        compose:
          services:
            rabbit-workshop:
              image: "rabbitmq:management"
              ports:
                - "5672:5672"
                - "15672:15672"
    dashboards:
      - name: Editor
      - name: Terminal
