name: Publish Workshops
run-name: Publish Workshop Content and Configuration from ${{ github.ref_name }} to GHCR

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "workshops/**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish-workshop:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Workshops
        uses: spring-academy/spring-academy-github-actions/publish-workshop@v7
        with:
          token: ${{secrets.GITHUB_TOKEN}}
